image: node:latest

stages:
  - test
  - deploy

cache:
  paths:
  - node_modules/

Code Style:
  script:
      - npm test
  type: test

Deploy:
  environment:
    name: production
    url: https://tolookat.me/gog-promo
  script:
      - ./bin/deploy.sh
  type: deploy
  only:
  - master
