image: node:latest

stages:
  - test
  - deploy

cache:
  paths:
  - node_modules/

Code Style:
  script:
      - npm run code-style
  type: test

Tests:
  script:
      - npm test
  type: test

NPM Security Check:
  script:
      - npm run check
  type: test
  allow_failure: true

Deploy:
  environment:
    name: production
    url: https://tolookat.me/gog-promo
  script:
      - ./bin/deploy.sh
  type: deploy
  only:
  - master
